name: node_lint

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  node_lint:
    name: check code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies at client
        run: cd client && npm install && cd -
      - name: Install dependencies at functions
        run: cd functions && npm install && cd -
      - name: Install dependencies at root
        run: npm install
      - name: Check lint
        run: npx lint-staged
      - name: Check type setting
        run: npm run typecheck
